{
 "title": "OKG Metrics Statics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(okg_gameserversets_replicas_count, gssNs)"
    }
   },
   {
    "name": "gssName",
    "query": {
     "query": "label_values(okg_gameserversets_replicas_count, gssName) "
    }
   },
   {
    "name": "gsName",
    "query": {
     "query": "label_values(okg_gameserver_deletion_priority, gsName) "
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GameServers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "sum(okg_gameservers_state_count)",
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Ready GameServers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "max(okg_gameservers_state_count{state=\"Ready\"})",
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Maintaining GameServers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "max(okg_gameservers_opsState_count{opsState=\"Maintaining\"})",
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "WaitToBeDeleted GameServers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "max(okg_gameservers_opsState_count{opsState=\"WaitToBeDeleted\"})",
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "GameServer State (now)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "max(okg_gameservers_state_count{state!=\"\"}) by (state)",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{state}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "GameServer OpsState (now)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "max(okg_gameservers_opsState_count) by (opsState)",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{opsState}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "Deleting GameServers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "max(okg_gameservers_state_count{state=\"Deleting\"})",
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Updating GameServers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "max(okg_gameservers_state_count{state=\"Updating\"})",
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "NotReady GameServers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "max(okg_gameservers_state_count{state=\"NotReady\"})",
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Existed GameServers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "max(okg_gameservers_total)",
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "GameServer State (Time series)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "max(okg_gameservers_state_count{state!=\"\"}) by (state)",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{state}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "GameServer OpsState (Time series)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "max(okg_gameservers_opsState_count) by (opsState)",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{opsState}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "GameServer Deletion Priority",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "max(okg_gameserver_deletion_priority{gsNs=~\"$namespace\",gsName=~\"$gsName\"}) by (gsNs,gsName)",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{gsNs}}/{{gsName}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "GameServer Update Priority",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "max(okg_gameserver_update_priority{gsNs=~\"$namespace\",gsName=~\"$gsName\"}) by (gsNs,gsName)",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{gsNs}}/{{gsName}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "The Number of Current Gs in GameServerSet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "max(okg_gameserversets_replicas_count{gsStatus=\"current\",gssNs=~\"$namespace\",gssName=~\"$gssName\"}) by (gssNs,gssName)",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{gssNs}}/{{gssName}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "The Number of Available Gs in GameServerSet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "max(okg_gameserversets_replicas_count{gsStatus=\"available\",gssNs=~\"$namespace\",gssName=~\"$gssName\"}) by (gssNs,gssName)",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{gssNs}}/{{gssName}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "The Number of Maintaining Gs in GameServerSet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "max(okg_gameserversets_replicas_count{gsStatus=\"maintaining\",gssNs=~\"$namespace\",gssName=~\"$gssName\"}) by (gssNs,gssName)",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{gssNs}}/{{gssName}}",
     "method": "GET"
    }
   ]
  },
  {
   "title": "The Number of WaitToBeDeleted Gs in GameServerSet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "max(okg_gameserversets_replicas_count{gsStatus=\"waitToBeDeleted\",gssNs=~\"$namespace\",gssName=~\"$gssName\"}) by (gssNs,gssName)",
     "fields": [
      { "jsonPath": "" }
     ],
     "legendFormat": "{{gssNs}}/{{gssName}}",
     "method": "GET"
    }
   ]
  }
 ]
}